# Generated by Django 2.0.7 on 2018-09-01 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_auto_20180827_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='size1',
        ),
        migrations.RemoveField(
            model_name='art',
            name='size2',
        ),
        migrations.RemoveField(
            model_name='art',
            name='size3',
        ),
        migrations.AddField(
            model_name='art',
            name='size',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
