# Generated by Django 2.0.7 on 2018-09-01 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_auto_20180901_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='detail',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='art',
            name='preview',
            field=models.CharField(max_length=500),
        ),
    ]
