# Generated by Django 2.0.7 on 2018-09-01 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_auto_20180901_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='artist',
        ),
    ]
