# Generated by Django 2.0.7 on 2018-09-04 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_remove_art_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rental.Artist'),
            preserve_default=False,
        ),
    ]
