# Generated by Django 2.0.7 on 2018-09-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_art_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='view',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
